// This file is generated by Firebase Studio.
'use server';
/**
 * @fileOverview A testimonial generator AI agent.
 *
 * - generateTestimonial - A function that handles the testimonial generation process.
 * - TestimonialInput - The input type for the generateTestimonial function.
 * - TestimonialOutput - The return type for the generateTestimonial function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const TestimonialInputSchema = z.object({
  productName: z.string().describe('The name of the product.'),
});
export type TestimonialInput = z.infer<typeof TestimonialInputSchema>;

const TestimonialOutputSchema = z.object({
  testimonial: z.string().describe('A simulated user testimonial.'),
  author: z.string().describe('The author of the testimonial.'),
});
export type TestimonialOutput = z.infer<typeof TestimonialOutputSchema>;

export async function generateTestimonial(input: TestimonialInput): Promise<TestimonialOutput> {
  return testimonialGeneratorFlow(input);
}

const prompt = ai.definePrompt({
  name: 'testimonialGeneratorPrompt',
  input: {schema: TestimonialInputSchema},
  output: {schema: TestimonialOutputSchema},
  prompt: `You are a marketing expert specializing in writing user testimonials for products.

You will generate a user testimonial for the following product:

Product: {{{productName}}}

The testimonial should be positive and highlight the benefits of the product. Also create a simulated author for the testimonial.

Output should be formatted as:
{
  "testimonial": "testimonial text",
  "author": "author name"
}
`,
});

const testimonialGeneratorFlow = ai.defineFlow(
  {
    name: 'testimonialGeneratorFlow',
    inputSchema: TestimonialInputSchema,
    outputSchema: TestimonialOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
